//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderShip
    {
        public int id { get; set; }
        public Nullable<int> order_id { get; set; }
        public string ship_name { get; set; }
        public string ship_address { get; set; }
        public string ship_phone { get; set; }
        public string card_id { get; set; }
        public string bank { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
